version: "3.8"
services:
  frontend:
    image: node:18
    container_name: frontend-todo
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: npm run serve

  backend:
    image: alpine:latest  
    container_name: backend-atodo
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8096:8096"
