definitions:
  internal.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
swagger: "2.0"
info:
  title: Todo App
  version: 1.0.0
  contact: {}
paths:
  /todos:
    get:
      description: Gets all todos in the database
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/internal.Todo"
            type: array
        "500":
          description: failed to get all todos
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
      summary: Gets all todos
      tags:
        - todos
    post:
      consumes:
        - application/json
      description: Adds a new todo to the database
      parameters:
        - description: New todo object
          in: body
          name: todo
          required: true
          schema:
            $ref: "#/definitions/internal.Todo"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/internal.Todo"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
        "500":
          description: failed to create todo
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
      summary: Adds a todo
      tags:
        - todos
  /todos/{id}:
    delete:
      description: Deletes a specific todo by id
      parameters:
        - description: Todo ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "202":
          description: Todo deleted
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: object
        "500":
          description: failed to delete todo
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
      summary: Deletes a todo
      tags:
        - todos
    get:
      description: Get a specific todo by id
      parameters:
        - description: Todo ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/internal.Todo"
        "404":
          description: Todo not found
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
        "500":
          description: failed to get todo
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
      summary: Get a todo
      tags:
        - todos
    put:
      description: Changes the complete status or the title of the todo
      parameters:
        - description: Todo body to be updated
          in: body
          name: todo
          required: true
          schema:
            $ref: "#/definitions/internal.Todo"
      produces:
        - application/json
      responses:
        "201":
          description: Todo updated successfully
          schema:
            type: string
        "400":
          description: todo not found
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
        "404":
          description: invalid ID
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
        "500":
          description: failed to update todo
          schema:
            $ref: "#/definitions/internal.ErrorResponse"
      summary: Updates a todo
      tags:
        - todos
