name: TodoApp frontend

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  frontend-test:
    name: frontend-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run frontend tests
        run: npx cypress run --component
        working-directory: ./frontend/
        